### ISSUE TITLE
Some CSS errors are not detected if they are at the start of the file, but detected when they are in the middle (?)

### ISSUE THREAD

**Issue by Stvad** [csstree/validator#21]
Example:

This generates no errors:
```css
}  

.garden-link::before {
  content: "🦚"
 } 
```

This generates an error:
```css
.garden-link::before {
  content: "🦚"
 } 

}
```

More generally I seem to be able to put semi-arbitrary things at the start of the file...
