### ISSUE TITLE
Content counters are not recognized as valid CSS

### ISSUE THREAD

**Issue by bratekarate** [csstree/validator#24]
`content: counters(...)` does not work for me (csstree-validator v.1.6.0).

Example code:

```css
.some-class {
  content: counters(list-counter, ".") "."
}
```

Output:

```
Mismatch
  syntax: normal | none | [ <content-replacement> | <content-list> ] [ / <string> ]?
   value: counters(list-counter,".") "."
```
