### ISSUE TITLE
Add fix-suggestion

### ISSUE THREAD

**Issue by smelukov** [csstree/validator#5]
```css
.some
{
   color: rgb(255, 0, 255, 1);
}
```
In this example, alpha component is excess and validator will tell about it: `Mismatch syntax`
But, will be cool if validator will suggesting some fixes for these (and similar) cases:
```js
fixes: [
  'rgb(255, 0, 255);',
  'rgba(255, 0, 255, 1);'
]
```
Some other examples:
- add missed unit
```css
.some
{
   width: 10;
}
```
```js
fixes: [
  '10px'
]
```
- fix mistyped
```css
.some
{
   coor: rgb(255, 0, 255, 1);
}
```
```js
fixes: [
  'color'
]
```
